name: visualride
favicon: null
layout_spectrum: 0.9520463962107897
typography_spectrum: 0.5100801116786897
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.8384646947961301
  lightness: 0.4875925707165152
  saturation: 0.2862841570749879
  rhythmicContrast: 0.5847958878148347
purpose: []
